# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlI5q4hCGKgCmU0nVy4b-xpjl2bmDmHM
"""

!pip -q install pandas numpy scikit-learn openai

import json
import re
import os
import math
import uuid
from collections import Counter, defaultdict
from datetime import datetime

import numpy as np
import pandas as pd

# OPTIONAL: only needed if you want cheap real AI labeling
USE_LLM = True   # set to True if you want model-generated labels/descriptions
OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-4.1-mini"  # cheap small model

INPUT_PATH = "/content/jsondata226MVP.json"

# Your run config: this counts as retrieved object #2
RUN_CONFIG = {
    "brand": "generic-fashion-demo",         # change if you want
    "category": "fashion",                   # beauty / fashion / accessories / mixed
    "time_window": "uploaded scrape sample", # replace if you have a true date range
    "max_posts": 60,                         # keep demo small/fast
    "min_cluster_size": 2,                   # do not create 1-post trends unless needed
    "top_k_trends": 5,
    "theme_keywords": [
        "穿搭", "ootd", "夏日", "极简", "通勤", "芭蕾", "大码", "裙", "短袖",
        "衬衫", "牛仔", "复古", "甜妹", "仙女", "韩", "日系", "显瘦", "裤子"
    ]
}

client = None

if USE_LLM:
    from openai import OpenAI
    client = OpenAI(api_key=OPENAI_API_KEY)

def label_cluster_with_llm(posts):
    """
    Cheap optional model call:
    takes a small list of post titles and returns a trend label + description + confidence
    """
    if not USE_LLM or client is None:
        return None

    titles = [p["post_title"] for p in posts[:8]]
    prompt = f"""
You are labeling XHS trend clusters for a class assignment.

Given these post titles, return strict JSON with:
- label
- description
- confidence (low|medium|high)
- keywords (array of short strings)

Rules:
- label must be short and distinct
- description = 1 sentence
- do not invent evidence outside these titles
- if titles are mixed or noisy, lower confidence

Titles:
{json.dumps(titles, ensure_ascii=False, indent=2)}
"""
    try:
        resp = client.responses.create(
            model=OPENAI_MODEL,
            input=prompt
        )
        text = resp.output_text.strip()
        return json.loads(text)
    except Exception as e:
        print("LLM labeling failed:", e)
        return None

with open(INPUT_PATH, "r", encoding="utf-8") as f:
    raw = json.load(f)

print(f"Loaded {len(raw)} records")

df = pd.DataFrame(raw).copy()

# Normalize
df["post_title"] = df["title"].fillna("").astype(str).str.strip()
df["post_likes"] = pd.to_numeric(df["likes"], errors="coerce").fillna(0).astype(int) # Changed 'post_likes' to 'likes'
df["author_name"] = df["creator"].fillna("").astype(str).str.strip() # Changed 'author_name' to 'creator'

# Add synthetic fields to make the output more assignment-friendly
# Since your scrape lacks full text, comments, timestamps, etc., we stay honest and use available fields only.
df["post_id"] = [f"p{i+1:03d}" for i in range(len(df))]
df["engagement"] = df["post_likes"]  # basic metric based on available data
df["text_for_clustering"] = df["post_title"]

# Keep only non-empty titles
df = df[df["post_title"].str.len() > 0].reset_index(drop=True)

print(df[["post_id", "post_title", "post_likes"]].head(10))

def contains_theme(text, keywords):
    t = str(text).lower()
    return any(str(k).lower() in t for k in keywords)

retrieved_df = df[df["text_for_clustering"].apply(lambda x: contains_theme(x, RUN_CONFIG["theme_keywords"]))].copy()

# Fallback: if filter is too narrow, just take the most-liked posts
if len(retrieved_df) < 5:
    retrieved_df = df.sort_values("post_likes", ascending=False).head(RUN_CONFIG["max_posts"]).copy()
else:
    retrieved_df = retrieved_df.sort_values("post_likes", ascending=False).head(RUN_CONFIG["max_posts"]).copy()

retrieved_posts = retrieved_df.to_dict(orient="records")

print(f"Retrieved {len(retrieved_posts)} posts")
display(retrieved_df[["post_id", "post_title", "post_likes"]].head(20))

STOPWORDS = {
    "的","了","是","太","很","也","都","就","和","在","又","一个","一下","真的",
    "今天","夏天","分享","合集","日常","感觉","就是","来了","家人们","好看","喜欢",
    "女生","可以","大家","自己","真的","一下","款","穿搭","ootd"
}

EN_STOPWORDS = {
    "the","and","for","with","this","that","you","are","too","very","look","daily","life"
}

def extract_tokens(text):
    text = str(text).lower()

    # keep chinese chunks + ascii words
    zh_chunks = re.findall(r"[\u4e00-\u9fff]{1,6}", text)
    en_chunks = re.findall(r"[a-zA-Z][a-zA-Z0-9\-\_]{1,20}", text)

    tokens = []
    for tok in zh_chunks + en_chunks:
        tok = tok.strip().lower()
        if not tok:
            continue
        if tok in STOPWORDS or tok in EN_STOPWORDS:
            continue
        if len(tok) == 1:
            continue
        tokens.append(tok)

    # lightweight phrase boosts for common fashion patterns
    phrase_hits = []
    phrases = [
        "大码", "显瘦", "通勤", "极简", "复古", "甜妹", "芭蕾", "日系", "韩系", "牛仔",
        "短袖", "衬衫", "裙", "裤", "仙女", "夏日", "出游", "look", "vintage", "balletcore"
    ]
    for p in phrases:
        if p.lower() in text:
            phrase_hits.append(p.lower())

    return list(tokens + phrase_hits)

retrieved_df["tokens"] = retrieved_df["text_for_clustering"].apply(extract_tokens)
retrieved_df["token_count"] = retrieved_df["tokens"].apply(len)

display(retrieved_df[["post_id", "post_title", "tokens"]].head(15))

def jaccard(a, b):
    sa, sb = set(a), set(b)
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / len(sa | sb)

posts = retrieved_df.to_dict(orient="records")

clusters = []
used = set()

# greedy clustering by token overlap
for i, post in enumerate(posts):
    if post["post_id"] in used:
        continue

    cluster = [post]
    used.add(post["post_id"])

    for j in range(i + 1, len(posts)):
        other = posts[j]
        if other["post_id"] in used:
            continue

        sim = jaccard(post["tokens"], other["tokens"])

        # looser threshold because titles are short/noisy
        if sim >= 0.18 or len(set(post["tokens"]) & set(other["tokens"])) >= 2:
            cluster.append(other)
            used.add(other["post_id"])

    clusters.append(cluster)

# absorb tiny clusters into nearest larger cluster when possible
large_clusters = [c for c in clusters if len(c) >= RUN_CONFIG["min_cluster_size"]]
small_clusters = [c for c in clusters if len(c) < RUN_CONFIG["min_cluster_size"]]

for sc in small_clusters:
    spost = sc[0]
    best_idx = None
    best_score = 0
    for idx, lc in enumerate(large_clusters):
        sims = [jaccard(spost["tokens"], p["tokens"]) for p in lc]
        score = max(sims) if sims else 0
        if score > best_score:
            best_score = score
            best_idx = idx
    if best_idx is not None and best_score >= 0.12:
        large_clusters[best_idx].extend(sc)
    else:
        large_clusters.append(sc)

clusters = large_clusters
clusters = sorted(clusters, key=lambda c: sum(p["engagement"] for p in c), reverse=True)

print(f"Built {len(clusters)} raw clusters")
for idx, c in enumerate(clusters[:10], 1):
    print(f"\nCluster {idx} ({len(c)} posts)")
    for p in c[:5]:
        print("-", p["post_title"])

def heuristic_label(cluster):
    token_counts = Counter()
    for p in cluster:
        token_counts.update(p["tokens"])

    common = [t for t, _ in token_counts.most_common(6)]

    joined_titles = " ".join([p["post_title"] for p in cluster]).lower()

    # heuristic naming rules
    if "大码" in common or "显瘦" in common:
        return "Plus-Size / Flattering Fit Styling"
    if "通勤" in common:
        return "Commute / Office Outfit Styling"
    if "芭蕾" in common or "balletcore" in common:
        return "Balletcore-Inspired Summer Looks"
    if "极简" in common:
        return "Minimalist Black-and-White Dressing"
    if "复古" in common or "vintage" in common:
        return "Vintage / Retro Outfit Aesthetic"
    if "短袖" in common or "衬衫" in common:
        return "Summer Tops and Shirt Selection"
    if "裙" in common or "仙女" in common:
        return "Soft Feminine Dress Styling"
    if "牛仔" in common or "甜妹" in common:
        return "Denim Sweet-Girl Styling"
    if "出游" in common or "夏日" in common:
        return "Summer Travel Outfit Inspiration"

    if common:
        return " / ".join(common[:3]).title()
    return "Mixed Fashion Trend"

def heuristic_description(cluster, label):
    titles = [p["post_title"] for p in cluster[:3]]
    return f"Posts in this trend cluster around {label.lower()}, based on recurring titles such as: " + "；".join(titles)

def confidence_for_cluster(cluster):
    n = len(cluster)
    all_tokens = []
    for p in cluster:
        all_tokens.extend(p["tokens"])
    c = Counter(all_tokens)
    shared = sum(1 for _, v in c.items() if v >= 2)

    if n >= 4 and shared >= 3:
        return "high"
    if n >= 2 and shared >= 1:
        return "medium"
    return "low"

trend_objects = []
top_clusters = clusters[:RUN_CONFIG["top_k_trends"]]

for idx, cluster in enumerate(top_clusters, 1):
    llm_label = label_cluster_with_llm(cluster) if USE_LLM else None

    if llm_label:
        label = llm_label.get("label", f"Trend {idx}")
        description = llm_label.get("description", "")
        confidence = llm_label.get("confidence", "medium")
        keywords = llm_label.get("keywords", [])
    else:
        label = heuristic_label(cluster)
        description = heuristic_description(cluster, label)
        confidence = confidence_for_cluster(cluster)

        token_counts = Counter()
        for p in cluster:
            token_counts.update(p["tokens"])
        keywords = [t for t, _ in token_counts.most_common(5)]

    post_count = len(cluster)
    total_engagement = int(sum(p["engagement"] for p in cluster))
    avg_engagement = round(total_engagement / post_count, 2) if post_count else 0

    evidence_posts = []
    for p in sorted(cluster, key=lambda x: x["engagement"], reverse=True)[:5]:
        evidence_posts.append({
            "post_id": p["post_id"],
            "post_title": p["post_title"],
            "post_likes": int(p["post_likes"]),
            # Use .get() to avoid KeyError if 'post_url' is missing in the data
            "post_url": p.get("post_url", ""),
            "author_name": p["author_name"]
        })

    trend_objects.append({
        "trend_id": f"t{idx:02d}",
        "label": label,
        "description": description,
        "keywords": keywords,
        "post_count": post_count,
        "total_engagement": total_engagement,
        "avg_engagement": avg_engagement,
        "confidence": confidence,
        "evidence_posts": evidence_posts
    })

result = {
    "run_id": f"run_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}",
    "agent_name": "XHS Trend Object Builder",
    "brand": RUN_CONFIG["brand"],
    "category": RUN_CONFIG["category"],
    "time_window": RUN_CONFIG["time_window"],
    "trend_objects": trend_objects
}

print(json.dumps(result, ensure_ascii=False, indent=2)[:5000])

os.makedirs("/content/outputs", exist_ok=True)

trend_output_path = "/content/outputs/trend_objects.json"
with open(trend_output_path, "w", encoding="utf-8") as f:
    json.dump(result, f, ensure_ascii=False, indent=2)

run_log = {
    "run_id": result["run_id"],
    "prompt": (
        "From a set of XHS posts for a brand/category and time window, "
        "produce distinct trend objects (cluster + label) and attach evidence and basic metrics per trend."
    ),
    "retrieved_sources": [
        INPUT_PATH,
        "RUN_CONFIG(in-notebook)"
    ],
    "retrieval_summary": {
        "raw_records_loaded": int(len(df)),
        "records_retrieved_for_run": int(len(retrieved_df)),
        "brand": RUN_CONFIG["brand"],
        "category": RUN_CONFIG["category"],
        "time_window": RUN_CONFIG["time_window"]
    },
    "decision_type": "rules-first with optional LLM labeling",
    "decision_criteria": [
        "Group posts that share recurring title keywords/themes",
        "Prefer distinct trend clusters over duplicate labels",
        "Attach only evidence directly present in retrieved posts"
    ],
    "evidence_requirements": [
        "Each trend must include evidence_posts with post IDs/titles/URLs",
        "Each trend must include basic metrics: post_count, total_engagement, avg_engagement"
    ],
    "failure_mode": (
        "If evidence is weak or titles are too noisy, produce fewer trends and lower confidence "
        "instead of forcing precise labels."
    ),
    "decision_output_file": trend_output_path,
    "evidence_used": {
        t["trend_id"]: [p["post_id"] for p in t["evidence_posts"]]
        for t in trend_objects
    },
    "confidence": {t["trend_id"]: t["confidence"] for t in trend_objects},
    "next_step_suggestion": (
        "Reviewer should inspect labels, evidence quality, and duplicate/noise before using "
        "these trend objects in Module 2."
    ),
    "timestamp_utc": datetime.utcnow().isoformat()
}

run_log_path = "/content/outputs/run_log.json"
with open(run_log_path, "w", encoding="utf-8") as f:
    json.dump(run_log, f, ensure_ascii=False, indent=2)

feedback_template = [
    {
        "reviewer": "Classmate A",
        "run_id": result["run_id"],
        "correctness_quality": 4,
        "missing_info": "yes - maybe include date/time fields when available",
        "duplicates_noise": "no"
    },
    {
        "reviewer": "Classmate B",
        "run_id": result["run_id"],
        "correctness_quality": 3,
        "missing_info": "no",
        "duplicates_noise": "yes - one cluster may overlap with summer outfit styling"
    },
    {
        "reviewer": "Classmate C",
        "run_id": result["run_id"],
        "correctness_quality": 4,
        "missing_info": "no",
        "duplicates_noise": "no"
    }
]

feedback_path = "/content/outputs/feedback_template.json"
with open(feedback_path, "w", encoding="utf-8") as f:
    json.dump(feedback_template, f, ensure_ascii=False, indent=2)

print("Saved:")
print("-", trend_output_path)
print("-", run_log_path)
print("-", feedback_path)

print("\n=== TREND OBJECT SUMMARY ===\n")
for t in result["trend_objects"]:
    print(f"{t['trend_id']} | {t['label']}")
    print(f"  confidence: {t['confidence']}")
    print(f"  post_count: {t['post_count']}")
    print(f"  total_engagement: {t['total_engagement']}")
    print(f"  keywords: {', '.join(t['keywords'])}")
    print("  evidence:")
    for ep in t["evidence_posts"][:3]:
        print(f"    - {ep['post_id']}: {ep['post_title']} ({ep['post_likes']} likes)")
    print()